language: node_js
sudo: false
node_js:
- '8'
cache:
  apt: true
  directories:
  - node_modules
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  ssh_known_hosts: github.com
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_ed58dc80a8a3_key -iv $encrypted_ed58dc80a8a3_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git config --global user.name "tianyong90"
- git config --global user.email 412039588@qq.com
install:
- npm install -no-optional
script:
- npm run production
after_success:
- rsync -vzrtopg --progress -e ssh --delete ./dist/* $DEPLOY_USER@$DEPLOY_HOST:/data/wwwroot/wevue.org
